default_language_version:
  python: python3
ci:
  autofix_prs: true
  autoupdate_commit_msg: "[pre-commit.ci] pre-commit suggestions"
  autoupdate_schedule: quarterly
  skip: ["next-lint-website"]
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
        exclude: >
          (?x)(
            build|
            stubs|
            ^bot/templates/$|
            openassistant/templates|
            docs/docs/api/openapi\.json|
            scripts/postprocessing/regex_pii_detector\.py
          )
      - id: check-ast
      - id: check-yaml
        exclude: ^copilot/.*/addons/.*$
      - id: check-json
      - id: check-case-conflict
      - id: detect-private-key
      - id: fix-encoding-pragma
        args: [--remove]
      - id: forbid-submodules
      - id: mixed-line-ending
      - id: requirements-txt-fixer
      - id: check-executables-have-shebangs
      - id: check-shebang-scripts-are-executable
      - id: check-byte-order-marker
      - id: check-symlinks
      - id: check-merge-conflict
      - id: check-added-large-files
        args: [--maxkb=102400]
      - id: end-of-file-fixer
  - repo: https://github.com/psf/black
    rev: 24.10.0
    hooks:
      - id: black-jupyter
  - repo: https://github.com/pycqa/isort
    rev: 5.13.2
    hooks:
      - id: isort
        args: ["--profile", "black", "--filter-files"]
  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: v0.7.1
    hooks:
      - id: ruff
        args: ["--fix"]
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v4.0.0-alpha.8
    hooks:
      - id: prettier
        args: [--prose-wrap=always, --write, --ignore-path=.prettierignore]
  - repo: https://github.com/igorshubovych/markdownlint-cli
    rev: v0.39.0
    hooks:
      - id: markdownlint
        args: [--fix]
  - repo: https://github.com/hadolint/hadolint
    rev: v2.12.0
    hooks:
      - id: hadolint
  - repo: https://github.com/IamTheFij/docker-pre-commit
    rev: v3.0.1
    hooks:
      - id: docker-compose-check
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.13.0
    hooks:
      - id: mypy
  - repo: local
    hooks:
      - id: check-english-only
        name: Check for English-only content
        entry:
          "bash -c 'if [ ! -f hooks/check_english_only.py ]; then mkdir -p hooks
          && curl -sSfL -o hooks/check_english_only.py
          https://raw.githubusercontent.com/inoue0426/Check_nonEnglish_comments/main/check_english_only.py;
          fi && python hooks/check_english_only.py'"
        language: system
        types: [text]
        exclude: |
          (?x)(
            ^docs/locales/|
            ^.*/locale/|
            \.po$|
            \.mo$|
            ^data/|
            ^tests/fixtures/
          )
exclude: '^\.env$'
