name: python_env
channels:
  - defaults
  - conda-forge
dependencies:
  - pip=24.0
  - python=3.10.
  - pip:
      - matplotlib
      - jupyter
      - numpy
      - pandas
      - lxml
      - indra
      - pyautogen==0.2.31
      - DeepPurpose==0.1.5
      - rdkit==2023.9.6
      - bs4==0.0.1
      - python-dotenv
